### ISSUE TITLE
[FE] 프로젝트 초기 설정

### ISSUE THREAD

**Issue by aken-you** [aken-you/chatting#1]
## 설명

frontend에서 사용할 패키지 설치한다.

## Todo

- [x] react (with vite)
- [x] react-router-dom
- [x] typescript
- [x] axios
- [x] eslint, prettier
  - [x] eslint import 규칙 설정
- [x] styled-components
- [x] storybook
- [x] ts 절대 경로 설정
- [x] 프로젝트에 사용할 icon 추가
